DataTrainingWeb/DataTrainingWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include( 'app.urls' ) ),
]

DataTrainingWeb/app/urls.py
from django.conf.urls import url

from . import views

app_name = 'app'

urlpatterns = [
    #Views
    url(r'^index', views.loginView, name='login'),
    url(r'^managestudent', views.manageStudentView, name='manageStudent'),
    # url(r'^stdlist', views.stdListView, name='stdList'),
    # url(r'^home', views.homeView, name='home'),
    url(r'^training', views.trainingView, name='training'),
    url(r'^appadmin', views.adminView, name='appAdmin'),
    url(r'^managegroup', views.manageGroupView, name='manageGroup'),
    url(r'^training', views.trainingView, name='training'),
    #Actions
    url(r'^home', views.doLogin, name='doLogin'),
    url(r'^registered', views.addStudent, name='addStudent'),
    url(r'^studentupdated', views.updateStudent, name='updateStudent'),
    url(r'^studentdeleted', views.deleteStudent, name='deleteStudent'),
    url(r'^groupdeleted', views.deleteGroup, name='deleteGroup'),
    url(r'^index', views.doLogout, name='doLogout'),
    url(r'^registerd', views.addGroup, name='addGroup'),
    url(r'^selectgroup', views.selectGroup, name='selectGroup'),
]

DataTrainingWeb/app/templates/base_navigation_template.html
{% extends "base_template.html" %}

{% block navigation %}
<section class="navigation-bar">
  <div class="menu-position">
    <div class="ui secondary menu">
      <div class="right menu">
        <div class="ui horizontal list">
          <div class="item">
            <i class="circular user purple icon"></i>
              <div class="content" style="padding-right: 10px">
                <div class="ui header" style="color: white">{{ name }}</div>
              </div>
          </div>
        </div>

        <form action="{% url 'app:login' %}" method="post">
            {% csrf_token %}
          <button class="ui inverted grey button">
            Logout
          </button>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

DataTrainingWeb/app/templates/base_template.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>PANTIP - DATA TRAINING</title>

  <link href="../static/css/semantic.min.css" rel="stylesheet">
  <link href="../static/css/style.css" rel="stylesheet">
  <link href="../static/css/font-awesome.min.css" rel="stylesheet">

  <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
  <script src="semantic/dist/semantic.min.js"></script>
</head>

<body>
  <section>
    {% block navigation %}
    {% endblock %}
  </section>
<!--
  <section class="admin-content"> -->
  {% block add_content %}
  {% endblock %}
  <!-- </section> -->

  <section class="mybody">
    {% block content %}
    {% endblock %}
  </section>
</body>

</html>

DataTrainingWeb/app/templates/home-old.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
              <ul class="nav navbar-nav">
                  <li>
                    <span>{{ name }} &nbsp;&nbsp;&nbsp;</span>
                  </li>
                  <li>
                    <form action="{% url 'app:doLogout' %}" method="post">{% csrf_token %}
                      <input type="submit" value="logout"></input>
                    </form>
                  </li>
              </ul>
          </div>
      </div>
  </nav>
  <section class="container content-section text-center">
      <div class= "section">
        <div class= "row">
          <p>Header Over Here!</p>
        </div>
         <div class= "row">
          <div class="col-lg-4">
            <form action="{% url 'app:training' %}" method="post">{% csrf_token %}
              <input style="height:200px;width:200px" type="submit" class="btn btn-warning" value="Group 1">
            </form>
          </div>
          <div class="col-lg-4">
              <button style="height:200px;width:200px" type="button" class="btn btn-warning disabled">Group 2</button>
          </div>
          <div class="col-lg-4">
              <button style="height:200px;width:200px" type="button" class="btn btn-warning disabled">Group 3</button>
          </div>
         </div>
      </div>
  </section>
</body>
</html>

DataTrainingWeb/app/templates/home.html
{% extends "base_navigation_template.html" %}

{% block content %}
    <section>
        <h1 class="ui center aligned icon header" style="color:#F5F5F5">
          <img src="../static/images/pantip-icon.png" style="height: 17%; width: 17%">
            <div class="header" style="padding-top: 20px">
              Select the forum group!
            </div>
            <div>{{ msg }}</div>
        </h1>

        <div class="ui three column grid">
          <div class="row">
            {% for group in groups %}
              <div class="column">
                <form action="{% url 'app:selectGroup' %}" method="post">{% csrf_token %}
                  <div class="center-groupbtn">
                    <button class="massive ui inverted blue button" name="selectedGroup" value="{{ group.name }}">{{ group.name }}</button>
                  </div>
                </form>
              </div>
            {% endfor %}

            <!-- <div class="column">
              <form action="{% url 'app:training' %}" method="post">
              {% csrf_token %}
                <div class="center-groupbtn">
                  <button class="massive ui inverted blue button">Group 2</button>
                </div>
              </form>
            </div>

            <div class="column">
              <form action="{% url 'app:training' %}" method="post">
              {% csrf_token %}
                <div class="center-groupbtn puton">
                    <button class="massive ui disabled inverted blue button">
                      <i class="lock icon"></i>
                      Group 3
                    </button>
                </div>
              </form>
            </div>

            <div class="column">
              <form action="{% url 'app:training' %}" method="post">
              {% csrf_token %}
                <div class="center-groupbtn">
                    <button class="massive ui disabled inverted blue button">
                      <i class="lock icon"></i>
                      Group 4
                    </button>
                </div>
              </form>
            </div>

            <div class="column">
              <form action="{% url 'app:training' %}" method="post">
              {% csrf_token %}
                <div class="center-groupbtn">
                    <button class="massive ui disabled inverted blue button" value="5">
                      <i class="lock icon"></i>
                      Group 5
                    </button>
                </div>
              </form>
            </div>

            <div class="column">
              <form action="{% url 'app:training' %}" method="post">
              {% csrf_token %}
                <div class="center-groupbtn">
                    <button class="massive ui disabled inverted blue button">
                      <i class="lock icon"></i>
                      Group 6
                    </button>
                </div>
              </form>
            </div> -->

          </div>
        </div>
    </section>

{% endblock %}

DataTrainingWeb/app/templates/index-old.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <!-- <div class="grad"></div> -->
  <div><!-- class="header"> -->
    <div>Data<span>Training</span></div>
  </div>
  <br>
  <div> <!--  class="login"> -->
    {{ msg }}
    <form action="{% url 'app:doLogin' %}" method="post">
      {% csrf_token %}
      <input type="text" placeholder="username" name="Lusername"><br>
      <input type="password" placeholder="password" name="Lpassword"><br>
      <input type="submit" value="Login">
    </form>
  </div>
</body>
</html>

DataTrainingWeb/app/templates/index.html
{% extends "base_template.html" %}

{% block content %}

<div class="ui one column stackable center aligned page grid">
  <div class="column twelve wide">
    <h1>DATA TRAINING</h1>
    <h3>{{ msg }}<h3>
      <form action="{% url 'app:doLogin' %}" method="post">{% csrf_token %}
        <div class="ui form">
          <div class="field">
            <div class="ui left icon input">
              <input type="text" placeholder="Username" name="Lusername">
              <i class="user icon"></i>
            </div>
          </div>
          <div class="field">
            <div class="ui left icon input">
              <input type="password" placeholder="password" name="Lpassword">
              <i class="lock icon"></i>
            </div>
          </div>
          <input type="submit" value="LOGIN" class="ui blue submit button">
        </div>
      </form>
  </div>
</div>

{% endblock %}

DataTrainingWeb/app/templates/training-old.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
              <ul class="nav navbar-nav">
                  <li>
                      <span>{{ name }}</span>
                  </li>
                  <li>
                    <form action="{% url 'app:doLogout' %}" method="post">{% csrf_token %}
                      <input type="submit" value="logout"></input>
                    </form>
                  </li>
              </ul>
          </div>
      </div>
  </nav>
  <section class="container content-section text-center">

      <div class="progress">
          <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
              <span class="sr-only">60% Complete (warning)</span>
          </div>
      </div>

      <div class = "panel panel-info" style="min-height: 150px; max-height: 150px; width: 100%;">
        {{ SENTENCE }}
      </div>
  </section>

  <section class="container content-section text-center">
      <div class = "row">
        <div class = "col-lg-4 col-lg-offset-4">
          <p>WORD</p>
        </div>
        <div class = "col-lg-4 col-lg-offset-0">
          <a class="btn btn-circle">
            <i class="glyphicon glyphicon-chevron-right"></i>
          </a>
        </div>
      </div>

      <div class = "row">
        <div class = "col-lg-1 col-lg-offset-5">
          <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              n
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><a>noun</a></li>
            </ul>
          </div>
        </div>
        <div class = "col-lg-1">
          <a class="btn btn-default btn-lg">
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          </a>
        </div>
      </div>
  </section>
</body>
</html>

DataTrainingWeb/app/templates/training.html
{% extends "base_navigation_template.html" %}

{% block content %}
<div class="ui blue inverted progress">
  <div class="bar">
     <div class="progress"></div>
  </div>
</div>

<div class="ui raised very padded center aligned text container inverted segment">
  <p>This is the box of Sentences.</p>
</div>

<div class="ui two column stackable page grid">
  <div class="right floated left aligned six wide column">
    <div class="ui compact inverted circular segment">
      <h2 class="ui header">Word</h2>
    </div>
  </div>

  <div class="right aligned four wide column">
    <button class="massive ui circular icon inverted pink button">
      <i class="chevron right icon"></i>
    </button>
  </div>
</div>

<div class="ui two column stackable page grid">
  <div class="right floated left aligned two wide column">
    <select class="ui search dropdown">
      <option value="">POS</option>
      <option value="npn">npn</option>
      <option value="ncn">ncn</option>
      <option value="n">noun</option>
      <option value="pron">pron</option>
      <option value="vi">vi</option>
      <option value="vt">vt</option>
      <option value="verb">verb</option>
      <option value="det">det</option>
      <option value="adj">adj</option>
      <option value="adv">adv</option>
      <option value="advm1">advm1</option>
      <option value="cl">cl</option>
      <option value="conj">conj</option>
      <option value="prep">prep</option>
      <option value="int">int</option>
      <option value="pref">pref</option>
      <option value="part">part</option>
      <option value="neg">neg</option>
      <option value="punc">punc</option>
      <option value="idm">idm</option>
      <option value="psm">psm</option>
      <option value="sym">sym</option>
    </select>
  </div>

  <div class="left aligned eight wide column">
    <button class="ui icon button">
      <i class="checkmark icon"></i>
    </button>
  </div>
</div>

{% endblock %}